### ISSUE TITLE
Request to add more Dragon Ball Z quotes

### ISSUE THREAD

**Issue by AndyTheNerd** [RocktimSaikia/anime-chan#27]
Hey guys, I love this API! I use it for an integration in a Discord bot! I would like to request that more quotes be added from DBZ. It seems there's only one quote from Vegeta in the whole API. 

Apologies if this was posted in the wrong channel.
Thanks!

**Comment by RocktimSaikia** [comment]
@AndyTheNerd Ah I see. I did notice that . Not only DBZ but some other characters too. It has been a long time since I last updated the database with new quotes. I will definitely look into this issue and update the database very soon. Till then I am keeping this issue open. I will mention you once the database is updated.
Thanks for opening the issue :unicorn:

**Comment by RocktimSaikia** [comment]
Added. Animechan version 2.0.0 released. Old API will no longer function
