### ISSUE TITLE
API down again.

### ISSUE THREAD

**Issue by okay-retard** [RocktimSaikia/anime-chan#33]
Is it because dynos got over? No problem we will wait for January 😃

**Comment by RocktimSaikia** [comment]
Yes. Also, I am not actively maintaining the API right now due to my health issues. 
But the good news is that now I am hosting a mirror of the API in a mother server, So once the main server goes down, the other will get activated. But I have not implemented it in the backend yet. I Will do it in the future, but not sure when!

**Comment by okay-retard** [comment]
no problem and thanks...Btw can I host the same on my heroku? Idk how to though. Can you make a deploy button or something?

**Comment by techristy** [comment]
<function get_quote at 0x7f2e3b84c0d0> I get this when I try to use it on my bot. Any ideas as to what mistake I could've made?

**Comment by Kadantte** [comment]
@RocktimSaikia is it possible to host our deployment? if yes can you please provide me with the way you're putting quotes into ur database or share with us the database dumb if it's okay with your ofc!
