### ISSUE TITLE
animechan is down

### ISSUE THREAD

**Issue by melosh101** [rocktimsaikia/anime-chan#76]
hi if youre reading this you probably encountered the problem of the api being down.
dont worry, we know and are working towards fixing it. for now im hosting a temporary solution at [animechan.melosh.space](http://animechan.melosh.space/random)
note that it only supports http and not https and that the api root is based at / and not /random

**Comment by mertbozkir** [comment]
Thank you for everything you're doing! I'm looking forward to use this API 🤗

**Comment by YangLorenzo** [comment]
This is the problem I'm having, I'm not sure if this issue is related to my problem.

`Access to fetch at 'https://animechan.vercel.app/api/random' from origin 'https://animespot.vercel.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by rocktimsaikia** [comment]
Currently, I am extremely busy with work. So until I look into this issue, refer to @melosh101's solution.

**Comment by rocktimsaikia** [comment]
The API is now live with a new domain: https://animechan.xyz/. It is hosted on AWS, which entails significant maintenance and financial costs. The project may be discontinued if these costs escalate over time.

**Comment by melosh101** [comment]
i would be really sad to see the api to go. 😥 (dw guys ill find a way if push comes to shove)

**Comment by YangLorenzo** [comment]
Sorry, out of curiosity can I ask why you can't continue to use the free service provided by Vercel? I used your API for my school assignment and I deployed it to Vercel. anyway thanks for the API.

**Comment by rocktimsaikia** [comment]
@YangLorenzo All those free services (vercel, render) have bandwidth limit which Animechan crossed quite a while ago.

**Comment by faralost** [comment]
The service is down, is there a possibility that it will return back to work in near future?
